---
- hosts: bench
  become: yes
  gather_facts: no
  tasks:
    - name: change timezone to JST
      shell: cp -p /usr/share/zoneinfo/Japan /etc/localtime || true
    - group: name=wheel
    - user: name=isucon groups=wheel shell=/bin/bash
    - copy: src=../files/etc/profile.d/bashrc dest=/home/isucon/.profile owner=isucon mode=755
    - lineinfile: dest=/etc/sudoers state=present regexp='^%wheel ALL\=' line='%wheel ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
