version: '2.2'
services:
  nginx:
    image: nginx:1.22
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/public
    ports:
      - "80:80"
    links:
      - app

  app:
    cpus: 1
    mem_limit: 1g
    # Go実装の場合は golang/ PHP実装の場合は php/
    build: rust/
    environment:
      ISUCONP_DB_HOST: mysql
      ISUCONP_DB_PORT: 3306
      ISUCONP_DB_USER: root
      ISUCONP_DB_PASSWORD: root
      ISUCONP_DB_NAME: isuconp
      ISUCONP_MEMCACHED_ADDRESS: memcached:11211
      ISUCONP_REDIS_URL: redis:6379
    links:
      - mysql
      - memcached
    volumes:
      - ./public:/home/public
    init: true
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    cpus: 1
    mem_limit: 1g
    image: mysql/mysql-server:8.0
    environment:
      - "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql:/var/lib/mysql
      - ./etc/my.cnf:/etc/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  memcached:
    image: memcached:1.6

  redis:
    image: redis:7.0.0
    restart: always
    ports:
      - 6379:6379

volumes:
  mysql:
